<a href="https://colab.research.google.com/github/chabori02/deeplearning/blob/main/practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 리스트 내포 복습

In [ ]:
alpha = [ chr(n) for n in range(65,65+26) ]
print(alpha)

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']


# 사용자정의함수 복습

In [ ]:
def max_value(num1,num2):
    if num1>num2:
       return num1
    elif num1<num2:
       return num2
    else:
       return '두수가 같습니다.'

a = int(input('첫번째 수 입력: '))
b = int(input('두번째 수 입력: '))
print( max_value(a, b) )

첫번째 수 입력: -10
두번째 수 입력: 77
77


# 모듈화

In [ ]:
import calc
print(calc.abs(-3))
print(calc.pow(5))

3
25


In [ ]:
from calc import *
print(abs(-3))
print(pow(5))

3
25


# 미니 멀티 게임 프로그램

In [ ]:
def num_game():
    com = random.randint(1,30)
    print('숫자 맞히기 게임 시작!')
    print()
    while True:
        user = int(input('1~30 중에 숫자 맞춰봐 (종료 0)'))
        if user==0:
            break
        elif com==user:
            print('정답입니다!!')
            break
        elif user>com:
            print('더 작은 숫자를 입력하세요.')
        else:
            print('더 큰 숫자를 입력하세요.')

def gugudan_game():
    pass1 = 0
    fail2 = 0
    print('구구단 게임 시작 !')
    while True:
        sign=input('시작: 아무키나, 종료: 0 ')
        if sign=='0':
            break
        dan= random.randint(2,9)
        num= random.randint(1,9)
        print(f'{dan} x {num} = ',end='')
        answer=int(input())
        if answer==dan*num:
            pass1 += 1
            print(f'맞음! 누적정답:{pass1}')

        else:
            fail2 += 1
            print(f'실패! 누적실패:{fail2}')
    print(f'누적정답:{pass1} / 누적실패:{fail2}')

def game_369(n):
    str_num = str(n)
    count_369 = str_num.count('3') + str_num.count('6') + str_num.count('9')

    if count_369 > 0:
        print('짝!' * count_369)
    else:
        print(n)

import random
while True:
    num=int(input('1)숫자맞히기 2)구구단게임 3)369게임 0)종료 '))
    if num==0:
        break
    elif num == 1:
        num_game()
    elif num ==2:
        gugudan_game()
    elif num==3:
        n = int(input("숫자 입력: "))
        game_369(n)

1)숫자맞히기 2)구구단게임 3)369게임 0)종료1
숫자 맞히기 게임 시작!

1~30 중에 숫자 맞춰봐 (종료 0)15
더 작은 숫자를 입력하세요.
1~30 중에 숫자 맞춰봐 (종료 0)7
더 작은 숫자를 입력하세요.
1~30 중에 숫자 맞춰봐 (종료 0)5
더 작은 숫자를 입력하세요.
1~30 중에 숫자 맞춰봐 (종료 0)3
더 큰 숫자를 입력하세요.
1~30 중에 숫자 맞춰봐 (종료 0)4
정답입니다!!
1)숫자맞히기 2)구구단게임 3)369게임 0)종료2
구구단 게임 시작 !
시작: 아무키나, 종료: 0 
9 x 3 = 27
맞음! 누적정답:1
시작: 아무키나, 종료: 0 
3 x 3 = 9
맞음! 누적정답:2
시작: 아무키나, 종료: 0 
2 x 7 = 10
실패! 누적실패:1
시작: 아무키나, 종료: 0 0
누적정답:2 / 누적실패:1
1)숫자맞히기 2)구구단게임 3)369게임 0)종료3
숫자 입력: 33333
짝!짝!짝!짝!짝!
1)숫자맞히기 2)구구단게임 3)369게임 0)종료0


# 람다함수 복습

In [ ]:
def flunk(x):
    return x < 60
score = [35, 67, 45, 21, 81]
result = list(filter(flunk, score))
print(result)

[35, 45, 21]


In [ ]:
score = [35, 67, 45, 21, 81]
result = list(filter(lambda x: x<60, score))
print(result)

[35, 45, 21]


In [ ]:
def half(x):
    return x / 2
score = [35, 67, 45, 21, 81]
result = list(map(half, score))
print(result)

[17.5, 33.5, 22.5, 10.5, 40.5]


In [ ]:
score = [35, 67, 45, 21, 81]
result = list(map(lambda x: x/2, score))
print(result)

[17.5, 33.5, 22.5, 10.5, 40.5]


In [ ]:
files = ['color','happy.png','sky.jpg','spec.xslx','report.hwp']
exp = list(filter( lambda x: '.jpg' in x or '.png' in x, files))
print(exp)

['happy.png', 'sky.jpg']


# 정규표현식

In [ ]:
import re
re.match('Hello', 'Hello, world!')

<re.Match object; span=(0, 5), match='Hello'>

In [ ]:
re.match('Python', 'Hello, world!')

In [ ]:
re.search('^Hello', 'Hello, world!')

<re.Match object; span=(0, 5), match='Hello'>

In [ ]:
re.search('world!$', 'Hello, world!')

<re.Match object; span=(7, 13), match='world!'>

In [ ]:
re.match('hello|world', 'hello')

<re.Match object; span=(0, 5), match='hello'>

In [ ]:
re.search('[0-9]*', 'an1357dec')

<re.Match object; span=(0, 0), match=''>

In [ ]:
re.match('[0-9]+', '1234')

<re.Match object; span=(0, 4), match='1234'>

In [ ]:
re.match('a*b', 'b')

<re.Match object; span=(0, 1), match='b'>

In [ ]:
re.match('a+b', 'aaab')

<re.Match object; span=(0, 4), match='aaab'>

In [ ]:
re.match('abc?d', 'abcd')

<re.Match object; span=(0, 4), match='abcd'>

In [ ]:
re.match('ab.d', 'abad')

<re.Match object; span=(0, 4), match='abad'>

In [ ]:
re.match('(hello){3}', 'hellohellohelloworld')

<re.Match object; span=(0, 15), match='hellohellohello'>

In [ ]:
re.match('[0-9]{3}-[0-9]{4}-[0-9]{4}','010-1000-1000')

<re.Match object; span=(0, 13), match='010-1000-1000'>

In [ ]:
re.match('\d{3}-\d{4}-\d{4}','010-1000-1000')

<re.Match object; span=(0, 13), match='010-1000-1000'>

In [ ]:
re.match('[a-zA-z0-9]+', 'Hello1234')

<re.Match object; span=(0, 9), match='Hello1234'>

In [ ]:
re.match('[가-힣]+', '홍길동')

<re.Match object; span=(0, 3), match='홍길동'>

In [ ]:
re.search('^[A-Z]+', 'Hello')

<re.Match object; span=(0, 1), match='H'>

In [ ]:
re.search('\*+', '1 ** 2')

<re.Match object; span=(2, 4), match='**'>

In [ ]:
re.search('^[A-Za-z]{2}', 'hello')

<re.Match object; span=(0, 2), match='he'>

In [ ]:
re.search('^[A-Za-z]{2,}', 'hello world')

<re.Match object; span=(0, 5), match='hello'>

In [ ]:
re.search('[~!*]{2}$', 'Hello Python#~!')

<re.Match object; span=(13, 15), match='~!'>

In [ ]:
text = 'Hello World'
re.match('^[A-Za-z]{2,}',text).group()

'Hello'

In [ ]:
result = re.findall('[A-Za-z]{2,}', text)
print(result)

['Hello', 'World']


In [ ]:
import re
pattern = r'^010-\d{3,4}-\d{4}$'
while True:
    phone = input('폰번호 입력: ')
    if phone == '0': break
    if re.match(pattern, phone) != None:
        print('폰번호 맞음\n')
    else:
        print('폰번호 틀림\n')

폰번호 입력: 010-1234-1234
폰번호 맞음

폰번호 입력: 010
폰번호 틀림

폰번호 입력: 0


In [ ]:
pattern = r'\d{6}-[1-6]\d{6}'
while True:
    phone = input('주민번호 입력: ')
    if phone == '0': break
    if re.match(pattern, phone) != None:
        print('주민번호 맞음\n')
    else:
        print('주민번호 틀림\n')

주민번호 입력: 123456-211111
주민번호 틀림

주민번호 입력: 123645-2111111
주민번호 맞음

주민번호 입력: 123456-0112111
주민번호 틀림

주민번호 입력: 0


#넘파이 라이브러리

In [ ]:
import numpy as np

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
b=np.zeros((3,3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
a=np.ones(10)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
b=np.ones((3,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
a=np.arange(1,11)
print( type(a) )

<class 'numpy.ndarray'>


In [ ]:
a=np.random.random((2,2))
print(a)

[[0.57296663 0.61472621]
 [0.74499482 0.32690466]]


In [ ]:
a=np.random.randint(1,10)
print( type(a) )

<class 'int'>


In [ ]:
a=np.random.randint(1,10,(2,2))
print( a )
print(type(a))

[[9 8]
 [5 7]]
<class 'numpy.ndarray'>


In [ ]:
a=np.random.rand(2,2)
print(a)

[[0.01796589 0.89110338]
 [0.12843863 0.9655324 ]]


In [ ]:
arr=np.arange(1,6)
print(arr)
print('ndim:',arr.ndim)
print('shape:',arr.shape)
print('size:',arr.size)
print('itemsize:',arr.itemsize)
print('dtype:',arr.dtype)
print('nbytes:',arr.nbytes)

[1 2 3 4 5]
ndim: 1
shape: (5,)
size: 5
itemsize: 8
dtype: int64
nbytes: 40


In [ ]:
a1 = np.arange(9)
print(a1)

[0 1 2 3 4 5 6 7 8]


In [ ]:
print(a1[1])

1


In [ ]:
print(a1[-1])

8


In [ ]:
a1[0]=10
print(a1)

[10  1  2  3  4  5  6  7  8]


In [ ]:
a2 = np.arange(6).reshape((2, 3))
print(a2)

[[0 1 2]
 [3 4 5]]


In [ ]:
print(a2[1,1])

4


In [ ]:
a2[0,0]=10
print(a2)

[[10  1  2]
 [ 3  4  5]]


In [ ]:
a1=np.arange(6)
print(a1)

[0 1 2 3 4 5]


In [ ]:
print(a1[1:])

[1 2 3 4 5]


In [ ]:
print(a1[-2:])

[4 5]


In [ ]:
print(a1[:-3])

[0 1 2]


In [ ]:
print(a1[::3])

[0 3]


In [ ]:
print(a1[::-1])

[5 4 3 2 1 0]


In [ ]:
a2=np.arange(1, 25).reshape((3, 8))
print(a2[1])
print()
print(a2[1:])
print()
print(a2[1:3,1:4])
print()
print(a2[:3,:3])
print()
print(a2[::2,1::3])
print()
print(a2[2:,::-2])

[ 9 10 11 12 13 14 15 16]

[[ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]

[[10 11 12]
 [18 19 20]]

[[ 1  2  3]
 [ 9 10 11]
 [17 18 19]]

[[ 2  5  8]
 [18 21 24]]

[[24 22 20 18]]


In [ ]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
c = a[(a>2) & (a<10)]
print(c)

[3 4 5 6 7 8 9]


In [ ]:
d = a[(a<2) | (a>3)]
print(d)

[0 1 4 5 6 7 8 9]


In [ ]:
e = a[~(a%3==0)]
print(e)

[1 2 4 5 7 8]


In [ ]:
# 다음 코드를 완성하시오.
import numpy as np

arr=np.arange(1,21)

print('마지막 원소:',arr[-1])
print('모든원소의 합:',arr.sum())
print('모든원소의 평균:',arr.mean())
new_arr=arr.reshape(4,5)
print(new_arr)

마지막 원소: 20
모든원소의 합: 210
모든원소의 평균: 10.5
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [ ]:
import numpy as np
import time
a = np.arange(10000000)
result = 0
s=time.time()
for v in a:
    result += v
e=time.time()
print(result, e-s)  # 벡터연산 수행시간
s=time.time()
result=np.sum(a)
e=time.time()
print(result, e-s)  # 백터연산 수행시간

49999995000000 3.2903640270233154
49999995000000 0.012645244598388672


#판다스 라이브러리

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
arr = np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
df = pd.DataFrame(arr)
print(df)

   0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11


In [ ]:
name_list=['장은실','오경선','양숙희']
dept_list=['컴공','영어','수학']
df = pd.DataFrame({'이름':name_list,'점수':[90,80,95],'전공':dept_list})

print(df)

    이름  점수  전공
0  장은실  90  컴공
1  오경선  80  영어
2  양숙희  95  수학


In [ ]:
import pandas as pd
df = pd.read_csv('mobile.csv')
print(df)

  제조사  색상   가격
0  삼성  검정  100
1  엘지  골드   80
2  애플  핑크  150
3  구글  실버  120


In [ ]:
df = pd.read_csv('mobile.csv', index_col=0)
print(df)

     색상   가격
제조사         
삼성   검정  100
엘지   골드   80
애플   핑크  150
구글   실버  120


In [ ]:
df = pd.read_excel('weather2020-2021.xlsx')
df

날짜  평균기온  최저기온  최고기온
0   2020-01-01  -2.2  -6.5   0.3
1   2020-01-02   1.0  -0.7   3.8
2   2020-01-03  -0.1  -3.4   4.6
3   2020-01-04   1.2  -2.8   6.1
4   2020-01-05   1.3  -3.2   6.6
..         ...   ...   ...   ...
726 2021-12-27  -7.6 -12.9  -3.9
727 2021-12-28  -4.1  -8.5  -0.9
728 2021-12-29   0.4  -3.8   5.9
729 2021-12-30  -3.9  -6.8   0.2
730 2021-12-31  -6.7  -8.8  -3.9

[731 rows x 4 columns]

In [ ]:
df.shape

(731, 4)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 731 entries, 0 to 730
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype         
---  ------  --------------  -----         
 0   날짜      731 non-null    datetime64[ns]
 1   평균기온    731 non-null    float64       
 2   최저기온    731 non-null    float64       
 3   최고기온    731 non-null    float64       
dtypes: datetime64[ns](1), float64(3)
memory usage: 23.0 KB


In [ ]:
df.head(10)

날짜  평균기온  최저기온  최고기온
0 2020-01-01  -2.2  -6.5   0.3
1 2020-01-02   1.0  -0.7   3.8
2 2020-01-03  -0.1  -3.4   4.6
3 2020-01-04   1.2  -2.8   6.1
4 2020-01-05   1.3  -3.2   6.6
5 2020-01-06   3.1   0.6   4.6
6 2020-01-07   6.3   4.2   7.7
7 2020-01-08   2.4  -0.4   8.9
8 2020-01-09  -1.2  -3.1   2.0
9 2020-01-10  -0.6  -4.3   4.2

In [ ]:
df.tail(10)

날짜  평균기온  최저기온  최고기온
721 2021-12-22   2.2  -2.6   8.2
722 2021-12-23   2.7  -1.5   8.3
723 2021-12-24  -0.3  -7.3   3.2
724 2021-12-25 -11.7 -14.4  -7.3
725 2021-12-26 -12.1 -15.5  -7.3
726 2021-12-27  -7.6 -12.9  -3.9
727 2021-12-28  -4.1  -8.5  -0.9
728 2021-12-29   0.4  -3.8   5.9
729 2021-12-30  -3.9  -6.8   0.2
730 2021-12-31  -6.7  -8.8  -3.9

In [ ]:
df.index

RangeIndex(start=0, stop=731, step=1)

In [ ]:
df.columns

Index(['날짜', '평균기온', '최저기온', '최고기온'], dtype='object')

In [ ]:
df.describe()

평균기온        최저기온        최고기온
count  731.000000  731.000000  731.000000
mean    13.511628    9.505882   18.179070
std     10.091922   10.448899   10.057783
min    -14.900000  -18.600000  -10.700000
25%      5.800000    1.400000    9.950000
50%     13.700000    8.900000   19.000000
75%     22.650000   19.050000   26.600000
max     31.700000   27.800000   36.500000

In [ ]:
df['평균기온'].mean()

13.511627906976743

In [ ]:
df.sort_values(by='최고기온')

날짜  평균기온  최저기온  최고기온
373 2021-01-08 -14.9 -18.6 -10.7
372 2021-01-07 -14.5 -16.5  -8.4
374 2021-01-09 -12.2 -16.6  -7.5
725 2021-12-26 -12.1 -15.5  -7.3
724 2021-12-25 -11.7 -14.4  -7.3
..         ...   ...   ...   ...
573 2021-07-27  31.1  27.8  35.7
569 2021-07-23  31.2  27.2  35.8
571 2021-07-25  31.5  27.2  35.9
568 2021-07-22  31.2  26.5  35.9
570 2021-07-24  31.7  26.9  36.5

[731 rows x 4 columns]

In [ ]:
df.sort_values(by='평균기온', ascending=False)

날짜  평균기온  최저기온  최고기온
570 2021-07-24  31.7  26.9  36.5
571 2021-07-25  31.5  27.2  35.9
569 2021-07-23  31.2  27.2  35.8
572 2021-07-26  31.2  27.4  35.4
568 2021-07-22  31.2  26.5  35.9
..         ...   ...   ...   ...
724 2021-12-25 -11.7 -14.4  -7.3
725 2021-12-26 -12.1 -15.5  -7.3
374 2021-01-09 -12.2 -16.6  -7.5
372 2021-01-07 -14.5 -16.5  -8.4
373 2021-01-08 -14.9 -18.6 -10.7

[731 rows x 4 columns]

In [ ]:
bank = pd.read_csv('bank.csv', encoding='CP949')
bank['job'].value_counts(ascending=True)

student           153
housemaid         208
unemployed        223
entrepreneur      239
self-employed     256
retired           351
services          661
admin.            834
technician       1206
blue-collar      1499
management       1560
Name: job, dtype: int64

In [ ]:
#df['평균기온']
df.평균기온

0     -2.2
1      1.0
2     -0.1
3      1.2
4      1.3
      ... 
726   -7.6
727   -4.1
728    0.4
729   -3.9
730   -6.7
Name: 평균기온, Length: 731, dtype: float64

In [ ]:
df[['날짜','평균기온']]

날짜  평균기온
0   2020-01-01  -2.2
1   2020-01-02   1.0
2   2020-01-03  -0.1
3   2020-01-04   1.2
4   2020-01-05   1.3
..         ...   ...
726 2021-12-27  -7.6
727 2021-12-28  -4.1
728 2021-12-29   0.4
729 2021-12-30  -3.9
730 2021-12-31  -6.7

[731 rows x 2 columns]

In [ ]:
df.loc[500:515,['날짜','평균기온']]

날짜  평균기온
500 2021-05-15  22.1
501 2021-05-16  18.4
502 2021-05-17  15.3
503 2021-05-18  17.9
504 2021-05-19  19.9
505 2021-05-20  18.7
506 2021-05-21  16.0
507 2021-05-22  18.6
508 2021-05-23  19.5
509 2021-05-24  19.4
510 2021-05-25  15.3
511 2021-05-26  18.0
512 2021-05-27  15.8
513 2021-05-28  15.3
514 2021-05-29  15.4
515 2021-05-30  18.4

In [ ]:
df.iloc[500:510, [0,1]]

날짜  평균기온
500 2021-05-15  22.1
501 2021-05-16  18.4
502 2021-05-17  15.3
503 2021-05-18  17.9
504 2021-05-19  19.9
505 2021-05-20  18.7
506 2021-05-21  16.0
507 2021-05-22  18.6
508 2021-05-23  19.5
509 2021-05-24  19.4

In [ ]:
df[631:636]

날짜  평균기온  최저기온  최고기온
631 2021-09-23  20.9  16.9  25.9
632 2021-09-24  21.8  16.7  26.9
633 2021-09-25  21.2  18.7  23.1
634 2021-09-26  22.6  18.4  27.3
635 2021-09-27  21.6  18.7  25.0

In [ ]:
df.index = df['날짜']
df

날짜  평균기온  최저기온  최고기온
날짜                                     
2020-01-01 2020-01-01  -2.2  -6.5   0.3
2020-01-02 2020-01-02   1.0  -0.7   3.8
2020-01-03 2020-01-03  -0.1  -3.4   4.6
2020-01-04 2020-01-04   1.2  -2.8   6.1
2020-01-05 2020-01-05   1.3  -3.2   6.6
...               ...   ...   ...   ...
2021-12-27 2021-12-27  -7.6 -12.9  -3.9
2021-12-28 2021-12-28  -4.1  -8.5  -0.9
2021-12-29 2021-12-29   0.4  -3.8   5.9
2021-12-30 2021-12-30  -3.9  -6.8   0.2
2021-12-31 2021-12-31  -6.7  -8.8  -3.9

[731 rows x 4 columns]

In [ ]:
df.loc['2021-08-31',['평균기온','최저기온']]

평균기온    20.5
최저기온    18.1
Name: 2021-08-31 00:00:00, dtype: object

In [ ]:
df.iloc[610:620]

날짜  평균기온  최저기온  최고기온
날짜                                     
2021-09-02 2021-09-02  23.5  20.7  26.7
2021-09-03 2021-09-03  24.3  20.6  29.2
2021-09-04 2021-09-04  23.2  18.5  28.6
2021-09-05 2021-09-05  23.1  19.4  27.3
2021-09-06 2021-09-06  22.3  18.0  26.4
2021-09-07 2021-09-07  19.6  17.6  20.9
2021-09-08 2021-09-08  22.2  19.0  26.9
2021-09-09 2021-09-09  23.5  19.1  29.1
2021-09-10 2021-09-10  23.6  19.5  28.9
2021-09-11 2021-09-11  24.0  19.9  29.4

In [ ]:
df.iloc[631:633,0:2]

날짜  평균기온
날짜                         
2021-09-23 2021-09-23  20.9
2021-09-24 2021-09-24  21.8

In [ ]:
w = df['평균기온'] > 31
df[w]

날짜  평균기온  최저기온  최고기온
날짜                                     
2021-07-22 2021-07-22  31.2  26.5  35.9
2021-07-23 2021-07-23  31.2  27.2  35.8
2021-07-24 2021-07-24  31.7  26.9  36.5
2021-07-25 2021-07-25  31.5  27.2  35.9
2021-07-26 2021-07-26  31.2  27.4  35.4
2021-07-27 2021-07-27  31.1  27.8  35.7

In [ ]:
df[df['평균기온'] >= 31]

날짜  평균기온  최저기온  최고기온
날짜                                     
2021-07-22 2021-07-22  31.2  26.5  35.9
2021-07-23 2021-07-23  31.2  27.2  35.8
2021-07-24 2021-07-24  31.7  26.9  36.5
2021-07-25 2021-07-25  31.5  27.2  35.9
2021-07-26 2021-07-26  31.2  27.4  35.4
2021-07-27 2021-07-27  31.1  27.8  35.7

In [ ]:
w = df['최고기온'] == df['최고기온'].max()
df[w]

날짜  평균기온  최저기온  최고기온
날짜                                     
2021-07-24 2021-07-24  31.7  26.9  36.5

In [ ]:
w = df['최고기온'] - df['최저기온'] >= 15
df[w]

날짜  평균기온  최저기온  최고기온
날짜                                     
2020-02-11 2020-02-11   6.8  -0.5  14.6
2020-04-13 2020-04-13  12.4   4.3  20.4
2020-05-06 2020-05-06  19.4  11.1  27.6
2021-02-19 2021-02-19   1.6  -7.1   8.9
2021-02-26 2021-02-26   8.2   0.5  15.8
2021-03-10 2021-03-10   8.8   1.7  17.1
2021-03-17 2021-03-17   8.8   1.8  17.5
2021-03-26 2021-03-26  12.6   4.8  20.6
2021-03-31 2021-03-31  14.5   5.9  22.9
2021-04-21 2021-04-21  19.1  10.3  28.2
2021-05-06 2021-05-06  15.7   7.9  23.1
2021-05-11 2021-05-11  18.5   9.4  25.7
2021-05-30 2021-05-30  18.4  10.8  26.3

In [ ]:
df1 = pd.read_csv('signup.csv', encoding='cp949')
df1

수강코드    과목명 담당교수
0   111    파이썬  양숙희
1   222  데이터분석  오경선
2   333   인공지능  장은실
3   444   선형대수  황복동
4   555   이산수학  정명식
5   666  컴퓨터개론  최봉수
6   777   자료구조  김진영
7   888   정보통신  김진호

In [ ]:
df2=pd.read_csv('professor.csv', encoding='cp949')
df2

담당교수     학과
0  양숙희  컴퓨터공학
1  장은실   정보통신
2  오경선   인공지능
3  황복동  컴퓨터공학
4  정명식   인공지능

In [ ]:
pd.merge(df1,df2, on='담당교수')

수강코드    과목명 담당교수     학과
0   111    파이썬  양숙희  컴퓨터공학
1   222  데이터분석  오경선   인공지능
2   333   인공지능  장은실   정보통신
3   444   선형대수  황복동  컴퓨터공학
4   555   이산수학  정명식   인공지능

In [ ]:
df2.groupby('학과').count()

담당교수
학과         
인공지능      2
정보통신      1
컴퓨터공학     2

In [ ]:
df=pd.read_csv('covid.csv',encoding='cp949')
df

항목  사례수    증가    감소  변화없음
0    스마트폰  999  78.9   1.7  19.4
1    텔레비전  965  68.5   3.9  27.6
2  개인용 PC  973  65.7   3.7  30.6
3  태블릿 PC  662  46.8   4.2  49.0
4     라디오  687  35.5  12.5  52.0
5    잡지·책  776  31.3  17.8  50.9
6    종이신문  552  17.6  23.2  59.2

In [ ]:
w = df['사례수'] == df['사례수'].max()
df[w]

항목  사례수    증가   감소  변화없음
0  스마트폰  999  78.9  1.7  19.4

In [ ]:
new_data = df.sort_values('증가', ascending=False)
new_data.head(3)

항목  사례수    증가   감소  변화없음
0    스마트폰  999  78.9  1.7  19.4
1    텔레비전  965  68.5  3.9  27.6
2  개인용 PC  973  65.7  3.7  30.6